// <auto-generated />
using EFCoreDemo3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreDemo3.Migrations
{
    [DbContext(typeof(DemoThreeContext))]
    [Migration("20190702132857_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:Sequence:.sequ", "'sequ', '', '1000', '5', '', '', 'Int32', 'False'");

            modelBuilder.Entity("EFCoreDemo.Model.Xulie.Sequencess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sequencesses");
                });
#pragma warning restore 612, 618
        }
    }
}
