// <auto-generated />
using System;
using FirstEFCoreDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstEFCoreDemo.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190630101458_init5")]
    partial class init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EFCoreDemo.Model.Inheritance.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("PhoneId");

                    b.ToTable("Phone");

                    b.HasDiscriminator<string>("Type").HasValue("Phone");
                });

            modelBuilder.Entity("FirstEFCoreDemo.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BeiYongJian")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.HasAlternateKey("BeiYongJian");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("FirstEFCoreDemo.Models.BlogMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("BlogMetaDatas");
                });

            modelBuilder.Entity("FirstEFCoreDemo.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("FFF");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdateDate");

                    b.HasKey("PostId");

                    b.HasIndex("FFF");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFCoreDemo.Model.Inheritance.HuaWei", b =>
                {
                    b.HasBaseType("EFCoreDemo.Model.Inheritance.Phone");

                    b.Property<string>("HuaWeiContent");

                    b.HasDiscriminator().HasValue("HuaWei");
                });

            modelBuilder.Entity("EFCoreDemo.Model.Inheritance.XiaoMi", b =>
                {
                    b.HasBaseType("EFCoreDemo.Model.Inheritance.Phone");

                    b.Property<string>("XiaoMiContent");

                    b.HasDiscriminator().HasValue("XiaoMi");
                });

            modelBuilder.Entity("FirstEFCoreDemo.Models.Post", b =>
                {
                    b.HasOne("FirstEFCoreDemo.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("FFF")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
