namespace DbMigrationForDemo3
{
    public class Program
    {
        protected Program()
        {
        }

        static void Main(string[] args)
        {
            // Generated by DbMigration
        }
    }
}